name: story-storage-1
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libsqlite=3.51.1=hf5d6505_1
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.6.0=h725018a_0
  - pip=25.3=pyh145f28c_0
  - python=3.14.2=h4b44e0e_100_cp314
  - python_abi=3.14=8_cp314
  - tk=8.6.13=h2c6b04d_3
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - zstd=1.5.7=h534d264_6
prefix: C:\Users\U1\miniconda3\envs\story-storage-1
