name: story-storage-1
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.1=pyhd8ed1ab_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=h477c42c_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py314h909e829_3
  - cpython=3.14.2=py314hd8ed1ab_100
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.19=py314hb98de8c_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.4.0=hac47afa_0
  - executing=2.2.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=pyh7db6752_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=12.3.0=h5a1b470_0
  - icu=78.1=h637d24d_0
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.8.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kiwisolver=1.4.9=py314hf309875_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.7=default_ha2db4b5_3
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libglib=2.86.3=h0c9aed9_0
  - libgomp=15.2.0=h8ee18e1_16
  - libhwloc=2.12.1=default_h4379cf1_1003
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libpng=1.6.53=h7351971_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.1=hf5d6505_1
  - libtiff=4.7.1=h8f73337_1
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - matplotlib=3.10.8=py314h86ab7b2_0
  - matplotlib-base=3.10.8=py314hfa45d96_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.3.0=hac47afa_454
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.4.0=py314h06c3c77_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314hd8fd7ce_2
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.47=hd2b5f0e_0
  - pillow=12.1.0=py314h61b30b5_0
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py314hc5dbbe4_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyside6=6.10.1=py314h2c9462b_0
  - python=3.14.2=h4b44e0e_100_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.14.2=h4df99d1_100
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py314h8f8f202_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.10.1=h68b6638_4
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py314h2dcd201_0
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.4=py314h5a2d7ad_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py314h5a2d7ad_1
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - zeromq=4.3.5=h5bddc39_9
  - zlib-ng=2.3.2=h0261ad2_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - scipy==1.16.3
prefix: C:\Users\U1\miniconda3\envs\story-storage-1
